import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/Navbar";
import { ShootingStarsAndStarsBackgroundDemo } from "@/components/ui/ShootingStarsAndStarsBackgroundDemo";
import { CartProvider } from '@/context/cartContext';
import { UserProvider } from '@/context/userContext';
import { CouponPurchaseProvider } from '@/context/couponPurchaseContext';
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zoya Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <UserProvider>
          <CartProvider>
            <CouponPurchaseProvider>
              <NavigationMenuDemo />
              <ShootingStarsAndStarsBackgroundDemo  />
              <div className="relative z-10">{children}</div>
              <Toaster />
            </CouponPurchaseProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}

